export type Product = {
  id: string
  slug: string
  name: string
  description: string
  price: number
  mrp: number
  discount: number
  category: string
  sku: string
  color: string
  sizes: string[]
  images: string[]
  fabric: string
  occasion: string
  rating: number
  reviews: number
  badge: string
  stock: Record<string, number>
}

export const products: Product[] = [
  {
    id: "69ba28a30b819d3f52ce23a2",
    slug: "azure-leaf-hand-embroidered-shirt",
    name: "Azure Leaf Hand-Embroidered Shirt",
    description:
      "A breezy sky-blue shirt adorned with intricate, oversized leaf embroidery, capturing the essence of nature in elegant threads. Perfect for adding a fresh, artistic touch to your wardrobe.",
    price: 2100,
    mrp: 2390,
    discount: 12,
    category: "Contemporary",
    sku: "M26/SS/CON/CS/23",
    color: "Sky Blue",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Azure_Leaf_Hand-Embroidered_Shirt/Azure_Leaf_Hand-Embroidered_Shirt_main.jpg",
      "/assets/products/Azure_Leaf_Hand-Embroidered_Shirt/Azure_Leaf_Hand-Embroidered_Shirt_view_1.jpg",
      "/assets/products/Azure_Leaf_Hand-Embroidered_Shirt/Azure_Leaf_Hand-Embroidered_Shirt_view_2.jpg",
      "/assets/products/Azure_Leaf_Hand-Embroidered_Shirt/Azure_Leaf_Hand-Embroidered_Shirt_view_3.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Casual outings, garden parties, beach brunches, or daytime events where you want a relaxed yet stylish look.",
    rating: 4.3,
    reviews: 24,
    badge: "New",
    stock: {
      XS: 4,
      S: 3,
      M: 3,
      L: 3,
      XL: 4,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b945bd07dee5c7ea02d951",
    slug: "deep-sea-coco-hand-embroidered-shirt",
    name: "Deep Sea Coco Hand Embroidered Shirt",
    description:
      "A rich sea blue shirt featuring elegant coconut tree hand embroidery. The deep tone combined with tropical detailing creates a calm yet striking look, perfect for effortless style with a coastal touch.",
    price: 2399,
    mrp: 2499,
    discount: 4,
    category: "BeachSide",
    sku: "M26/SS/Beach/SF/22",
    color: "Deep Sea Mint",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_main.jpg",
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_view_1.jpg",
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_view_2.jpg",
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_view_3.jpg",
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_view_4.jpg",
      "/assets/products/Deep_Sea_COCO_Hand_Embroidered_Shirt/Deep_Sea_COCO_Hand_Embroidered_Shirt_view_5.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Vacations, beach days, resort wear, casual outings, and relaxed evening styling.",
    rating: 4.4,
    reviews: 41,
    badge: "Bestseller",
    stock: {
      XS: 7,
      S: 6,
      M: 6,
      L: 6,
      XL: 7,
      XXL: 8,
      XXXL: 9,
    },
  },
  {
    id: "69b9439007dee5c7ea02d8fd",
    slug: "true-red-havana-beach-embroidered-shirt",
    name: "True Red Havana Beach Embroidered Shirt",
    description:
      "A bold true red shirt featuring elegant coconut tree embroidery, inspired by tropical Havana vibes. The striking color paired with minimal beach-inspired detailing creates a perfect balance of statement and sophistication.",
    price: 1899,
    mrp: 2299,
    discount: 17,
    category: "BeachSide",
    sku: "M26/SS/Beach/SF/21",
    color: "True Red",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_main.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_1.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_2.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_3.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_4.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_5.jpg",
      "/assets/products/True_Red_havana_Beach_Embroidered_Shirt/True_Red_havana_Beach_Embroidered_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Vacations, beach outings, resort wear, evening get-togethers, and standout casual styling.",
    rating: 4.5,
    reviews: 58,
    badge: "Limited",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 11,
      XXXL: 12,
    },
  },
  {
    id: "69b941d407dee5c7ea02d8ac",
    slug: "coco-flamingo-beach-shirt",
    name: "Coco Flamingo Beach Shirt",
    description:
      "An off-white shirt featuring beautiful coconut tree embroidery on the front and back. The tropical-inspired design adds a breezy, beachy charm, making it a perfect blend of minimal style and vacation vibes.",
    price: 2799,
    mrp: 2999,
    discount: 7,
    category: "BeachSide",
    sku: "M26/SS/Beach/CS/20",
    color: "Off White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_main.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_1.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_2.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_3.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_4.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_5.jpg",
      "/assets/products/COCO_Flamingo_Beach_Shirt/COCO_Flamingo_Beach_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Beach days, vacations, resort wear, casual outings, and relaxed summer styling.",
    rating: 4.6,
    reviews: 75,
    badge: "New",
    stock: {
      XS: 13,
      S: 12,
      M: 12,
      L: 12,
      XL: 13,
      XXL: 2,
      XXXL: 3,
    },
  },
  {
    id: "69b9401907dee5c7ea02d82c",
    slug: "costal-king-hand-embroidered-shirt",
    name: "Costal King Hand Embroidered Shirt",
    description:
      "A pristine snow white shirt brought to life with intricate hand embroidery inspired by the sea. Featuring charming motifs like fish, sun, bottle, bird, and boat, each element adds a playful yet artistic touch, capturing the essence of coastal living in a unique and stylish way.",
    price: 2199,
    mrp: 2390,
    discount: 8,
    category: "BeachSide",
    sku: "M26/SS/Beach/SF/19",
    color: "Snow White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_main.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_1.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_2.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_3.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_4.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_5.jpg",
      "/assets/products/Costal_King_Hand_Embroidered_Shirt/Costal_King_Hand_Embroidered_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Vacations, beach days, casual outings, resort wear, and relaxed day styling.",
    rating: 4.7,
    reviews: 92,
    badge: "Bestseller",
    stock: {
      XS: 4,
      S: 3,
      M: 3,
      L: 3,
      XL: 4,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b93e1e07dee5c7ea02d7b1",
    slug: "pearl-white-red-spotted-shirt",
    name: "Pearl White Red Spotted Shirt",
    description:
      "A crisp pearl white shirt accented with delicate red embroidered lines, creating a subtle spotted effect. The fine detailing adds a touch of elegance while keeping the look clean and versatile—perfect for effortless styling.",
    price: 1399,
    mrp: 1599,
    discount: 13,
    category: "Contemporary",
    sku: "M26/SS/CON/CS/18",
    color: "Pearl White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Pearl_White_Red_Spotted_Shirt/Pearl_White_Red_Spotted_Shirt_main.jpg",
      "/assets/products/Pearl_White_Red_Spotted_Shirt/Pearl_White_Red_Spotted_Shirt_view_1.jpg",
      "/assets/products/Pearl_White_Red_Spotted_Shirt/Pearl_White_Red_Spotted_Shirt_view_2.jpg",
      "/assets/products/Pearl_White_Red_Spotted_Shirt/Pearl_White_Red_Spotted_Shirt_view_3.jpg",
      "/assets/products/Pearl_White_Red_Spotted_Shirt/Pearl_White_Red_Spotted_Shirt_view_4.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Workwear, casual outings, brunch dates, and minimal everyday styling.",
    rating: 4.8,
    reviews: 109,
    badge: "Limited",
    stock: {
      XS: 7,
      S: 6,
      M: 6,
      L: 6,
      XL: 7,
      XXL: 8,
      XXXL: 0,
    },
  },
  {
    id: "69b93c7907dee5c7ea02d769",
    slug: "sea-shore-leaf-shirt",
    name: "Sea Shore Leaf Shirt",
    description:
      "A soothing sky blue full-sleeve shirt with sea green tones, featuring delicate leaf embroidery above the pocket. The minimal yet refreshing design captures a calm, coastal vibe, making it effortlessly stylish and easy to wear.",
    price: 1699,
    mrp: 1999,
    discount: 15,
    category: "Contemporary",
    sku: "M26/SS/CON/SF/12",
    color: "Sea Green",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_main.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_1.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_2.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_3.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_4.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_5.jpg",
      "/assets/products/Sea_Shore_Leaf_Shirt/Sea_Shore_Leaf_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Casual outings, beach days, vacations, day wear, and relaxed everyday styling.",
    rating: 4.3,
    reviews: 126,
    badge: "New",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 0,
      XXXL: 12,
    },
  },
  {
    id: "69b93ac507dee5c7ea02d6f8",
    slug: "matcha-green-artistic-shirt",
    name: "Matcha Green Artistic Shirt",
    description:
      "A refreshing matcha green shirt featuring unique hand embroidery of a scooter, coconut trees, and chairs. The artistic, travel-inspired design brings a relaxed and playful vibe, making it a standout piece with a story to tell.",
    price: 1899,
    mrp: 2299,
    discount: 17,
    category: "Contemporary",
    sku: "M26/SS/CON/SF/16",
    color: "Matcha Green",
    sizes: ["S", "M", "XL", "XXL", "L"],
    images: [
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_main.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_1.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_2.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_3.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_4.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_5.jpg",
      "/assets/products/Matcha_Green_Artistic_Shirt/Matcha_Green_Artistic_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Vacations, casual outings, brunch dates, day trips, and laid-back everyday styling.",
    rating: 4.4,
    reviews: 143,
    badge: "Bestseller",
    stock: {
      XS: 0,
      S: 12,
      M: 12,
      L: 12,
      XL: 0,
      XXL: 2,
      XXXL: 3,
    },
  },
  {
    id: "69b938bc07dee5c7ea02d68c",
    slug: "salmon-pink-hand-embroidered-shirt",
    name: "Salmon Pink Hand Embroidered Shirt",
    description:
      "A soft salmon pink full-sleeve shirt beautifully adorned with hand embroidery featuring sun, floral, pot, and bird motifs. The playful yet artistic detailing adds a lively charm, making it a standout piece with a touch of nature-inspired elegance.",
    price: 1899,
    mrp: 2299,
    discount: 17,
    category: "Contemporary",
    sku: "M26/SS/CON/SF/15",
    color: "Pink",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Salmon_Pink_Hand_Embroidered_Shirt/Salmon_Pink_Hand_Embroidered_Shirt_main.jpg",
      "/assets/products/Salmon_Pink_Hand_Embroidered_Shirt/Salmon_Pink_Hand_Embroidered_Shirt_view_1.jpg",
      "/assets/products/Salmon_Pink_Hand_Embroidered_Shirt/Salmon_Pink_Hand_Embroidered_Shirt_view_2.jpg",
      "/assets/products/Salmon_Pink_Hand_Embroidered_Shirt/Salmon_Pink_Hand_Embroidered_Shirt_view_3.jpg",
      "/assets/products/Salmon_Pink_Hand_Embroidered_Shirt/Salmon_Pink_Hand_Embroidered_Shirt_view_4.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Casual outings, brunch dates, day events, vacations, and creative everyday styling.",
    rating: 4.5,
    reviews: 160,
    badge: "Limited",
    stock: {
      XS: 4,
      S: 0,
      M: 0,
      L: 0,
      XL: 4,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b9376907dee5c7ea02d625",
    slug: "maroon-handcrafted-arro-shirt",
    name: "Maroon Handcrafted Arro Shirt",
    description:
      "A rich maroon handcrafted shirt featuring subtle arrow-inspired embroidery. The fine detailing adds a unique geometric charm while keeping the look minimal and versatile. Perfect for those who appreciate understated craftsmanship with a modern touch.",
    price: 1399,
    mrp: 1599,
    discount: 13,
    category: "Contemporary",
    sku: "M26/SS/CON/SS/14",
    color: "Maroon",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_main.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_1.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_2.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_3.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_4.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_5.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_6.jpg",
      "/assets/products/Maroon_Handcrafted_Arro_Shirt/Maroon_Handcrafted_Arro_Shirt_view_7.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Casual outings, workwear, evening meet-ups, and smart everyday styling.",
    rating: 4.6,
    reviews: 177,
    badge: "New",
    stock: {
      XS: 7,
      S: 6,
      M: 6,
      L: 6,
      XL: 7,
      XXL: 8,
      XXXL: 9,
    },
  },
  {
    id: "69b935a907dee5c7ea02d5c3",
    slug: "the-bract-hand-embroidered-rust-cotton-linen-shirt",
    name: "The Bract Hand Embroidered Rust Cotton Linen Shirt",
    description:
      "A beautifully handcrafted rust cotton linen shirt adorned with two statement leaf embroideries. The bold yet minimal design adds a natural, earthy charm, making it a perfect blend of elegance and comfort for everyday wear.",
    price: 1699,
    mrp: 1999,
    discount: 15,
    category: "Nature",
    sku: "M26/SS/NATURE/SF/13",
    color: "Rust Color",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_main.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_1.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_2.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_3.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_4.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_5.jpg",
      "/assets/products/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt/The_Bract_hand_Embroidered_Rust_Cotton_linen_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Ideal for workdays, casual meet-ups, brunches, and understated festive styling.",
    rating: 4.7,
    reviews: 194,
    badge: "Bestseller",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 11,
      XXXL: 12,
    },
  },
  {
    id: "69b92ba507dee5c7ea02d213",
    slug: "flying-in-the-air-handcrafted-shirt",
    name: "Flying In The Air Handcrafted Shirt",
    description:
      'The design follows the journey of a bird in flight. On the chest, a hand-embroidered bird takes off, while at the bottom corner, a second motif grounded in intricate Kantha work adds a touch of playful asymmetry. The true soul of the piece lies on the back yoke, where the hand-stitched words "Flying in the Air" serve as a quiet reminder to embrace the breeze and the beauty of the present moment.',
    price: 1799,
    mrp: 1999,
    discount: 10,
    category: "Nature",
    sku: "M26/SS/NATURE/SF/12",
    color: "White",
    sizes: ["S", "M", "XL", "XXL", "L"],
    images: [
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_main.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_1.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_2.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_3.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_4.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_5.jpg",
      "/assets/products/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT/FLYING_IN_THE_AIR_HANDCRAFTED_SHIRT_view_6.jpg",
    ],
    fabric:
      "A premium blend of cotton and linen in an earthy, unbleached natural white—breathable, soft, and perfect for any climate.",
    occasion:
      "Casual outings, brunch dates, festive gatherings, and everyday elegance.",
    rating: 4.8,
    reviews: 31,
    badge: "Limited",
    stock: {
      XS: 13,
      S: 12,
      M: 12,
      L: 12,
      XL: 13,
      XXL: 2,
      XXXL: 3,
    },
  },
  {
    id: "69b9298e07dee5c7ea02d1c0",
    slug: "french-knotted-leaves-shirt",
    name: "French Knotted Leaves Shirt",
    description:
      "Elegant red handmade shirt featuring delicate French knot leaf embroidery. Each tiny leaf is intricately crafted, giving the piece a subtle textured charm. Perfect for adding a touch of artisanal beauty to your everyday style.",
    price: 1699,
    mrp: 1999,
    discount: 15,
    category: "Nature",
    sku: "M26/SS/NATURE/CS/11",
    color: "Red",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_main.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_1.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_2.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_3.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_4.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_5.jpg",
      "/assets/products/French_Knotted_Leaves_Shirt/French_Knotted_Leaves_Shirt_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Perfect for brunches, casual meet-ups, small festive occasions, and effortless daily wear.",
    rating: 4.3,
    reviews: 48,
    badge: "New",
    stock: {
      XS: 4,
      S: 3,
      M: 3,
      L: 3,
      XL: 4,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b927a207dee5c7ea02d173",
    slug: "the-life-tree-cotton-shirt",
    name: "The Life Tree Cotton Shirt",
    description:
      "Trees give peace to the souls of men to stay somewhere long.\r\nThis exquisite hand-embroidered shirt features two deeply rooted trees—one delicately stitched onto the front patch pocket, and its companion gracing the back. Like steadfast friends who have chosen their perfect place, these embroidered motifs work together to balance the garment, creating a beautiful and lasting sense of harmony.",
    price: 2799,
    mrp: 3099,
    discount: 10,
    category: "Nature",
    sku: "M26/SS/NATURE/CS/10",
    color: "Rust",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_main.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_1.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_2.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_3.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_4.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_5.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_6.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_7.jpg",
      "/assets/products/The_life_tree_cotton_shirt/The_life_tree_cotton_shirt_view_8.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.4,
    reviews: 65,
    badge: "Bestseller",
    stock: {
      XS: 7,
      S: 6,
      M: 6,
      L: 6,
      XL: 7,
      XXL: 8,
      XXXL: 9,
    },
  },
  {
    id: "69b924c107dee5c7ea02d0c3",
    slug: "the-solstice-hand-embroidered-artisan-shirt",
    name: "The Solstice Hand Embroidered Artisan Shirt",
    description:
      "Embrace effortless summer style with this Handcrafted Short-Sleeve Button-Down. Meticulously designed for the modern individual who appreciates artisanal detail, this shirt features a unique hand-embroidered sunburst motif on the chest, rendered in contrasting teal and white threads.\r\n\r\nThe charm lies in the craftsmanship: visible kantha-style pick stitching runs along the placket, adding a rugged, bespoke texture that sets it apart from mass-produced apparel. Cut from a breathable, lightweight fabric with a natural matte finish, it’s designed to keep you cool while looking polished.",
    price: 1899,
    mrp: 2299,
    discount: 17,
    category: "Nature",
    sku: "M26/SS/NATURE/SF/09",
    color: "SALMON PINK",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_main.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_1.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_2.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_3.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_4.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_5.jpg",
      "/assets/products/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT/THE_SOLSTICE_HAND_EMBROIDERED_ARTISAN_SHIRT_view_6.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion:
      "Perfect for golden hour gatherings, beachside brunches, or elevated daily wear.",
    rating: 4.5,
    reviews: 82,
    badge: "Limited",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 11,
      XXXL: 0,
    },
  },
  {
    id: "69b9236307dee5c7ea02d09d",
    slug: "the-solar-sol-shirt",
    name: "The Solar Sol Shirt",
    description:
      "Capture the essence of a warm Mediterranean sunset with this striking brown cotton-linen shirt. Designed for the man who appreciates artisanal detail, this piece features a hand-embroidered sun motif on the chest, radiating a relaxed, soulful energy. The Cuban collar and half-sleeves provide a classic, airy silhouette, while the intricate zigzag embroidery along the placket and hem adds a unique, handcrafted touch that sets it apart from the ordinary.",
    price: 1799,
    mrp: 1999,
    discount: 10,
    category: "Nature",
    sku: "M26/SS/NATURE/CS/08",
    color: "Brown",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_main.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_1.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_2.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_3.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_4.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_5.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_6.jpg",
      "/assets/products/THE_SOLAR_SOL_SHIRT/THE_SOLAR_SOL_SHIRT_view_7.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.6,
    reviews: 99,
    badge: "New",
    stock: {
      XS: 13,
      S: 12,
      M: 12,
      L: 12,
      XL: 13,
      XXL: 0,
      XXXL: 3,
    },
  },
  {
    id: "69b91f8e07dee5c7ea02cf5d",
    slug: "floral-pocket-shirt",
    name: "Floral Pocket Shirt",
    description:
      "The french knotted embellished floral motif on a patch pocket.\r\nFeaturing cuban collar half sleeve off white colored loose fit casual wear shirt.\r\nComfortable and breathable natural fabric for your breezy summers.",
    price: 1399,
    mrp: 1599,
    discount: 13,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/07",
    color: "White",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/FLORAL_POCKET_SHIRT/FLORAL_POCKET_SHIRT_main.jpg",
      "/assets/products/FLORAL_POCKET_SHIRT/FLORAL_POCKET_SHIRT_view_1.jpg",
      "/assets/products/FLORAL_POCKET_SHIRT/FLORAL_POCKET_SHIRT_view_2.jpg",
      "/assets/products/FLORAL_POCKET_SHIRT/FLORAL_POCKET_SHIRT_view_3.jpg",
      "/assets/products/FLORAL_POCKET_SHIRT/FLORAL_POCKET_SHIRT_view_4.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.7,
    reviews: 116,
    badge: "Bestseller",
    stock: {
      XS: 0,
      S: 3,
      M: 3,
      L: 3,
      XL: 0,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b91c7107dee5c7ea02ce85",
    slug: "the-aether-sky-blue-hand-stitched-artisan-shirt",
    name: 'The "Aether" Sky Blue Hand-Stitched Artisan Shirt',
    description:
      'A Breath of Artisanal Air\r\n\r\nInspired by the clear, expansive skies of a summer morning, this handcrafted sustainable cotton shirt is designed for the man who values both style and substance. Every inch of the garment tells a story of "slow fashion," where traditional techniques are repurposed for a modern, breezy silhouette.\r\n\r\nThe shirt features a delicate dance of textures: all-over French knot "butties" in a contrasting navy thread are hand-stitched across the body, creating a subtle 3D effect that catches the light. To ground the design, Kantha-work parallel stripes run vertically alongside the front placket, extending to the collar and back yoke. These rhythmic, hand-run stitches provide a structural elegance that highlights the shirt’s bespoke nature. Finished with natural wooden buttons, this piece isn\'t just a shirt—it\'s a wearable piece of art that keeps you cool while making a conscious statement.\r\n',
    price: 1899,
    mrp: 2299,
    discount: 17,
    category: "Floral",
    sku: "M26/SS/NATURE/CS/06",
    color: "Sky Blue",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_main.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_1.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_2.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_3.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_4.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_5.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_6.jpg",
      "/assets/products/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt/The_Aether_Sky_Blue_Hand-Stitched_Artisan_Shirt_view_7.jpg",
    ],
    fabric:
      "Premium, breathable sustainable cotton in a vibrant Pastel Sky Blue.",
    occasion:
      "Ideal for beach weddings, garden parties, or elevated weekend brunches.",
    rating: 4.8,
    reviews: 133,
    badge: "Limited",
    stock: {
      XS: 7,
      S: 0,
      M: 0,
      L: 0,
      XL: 7,
      XXL: 8,
      XXXL: 9,
    },
  },
  {
    id: "69b91a3607dee5c7ea02ce5b",
    slug: "mustard-floral-shirt",
    name: "Mustard Floral Shirt",
    description: "",
    price: 2099,
    mrp: 2299,
    discount: 9,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/05",
    color: "Brown",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_main.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_1.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_2.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_3.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_4.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_5.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_6.jpg",
      "/assets/products/Mustard_Floral_Shirt/Mustard_Floral_Shirt_view_7.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.3,
    reviews: 150,
    badge: "New",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 11,
      XXXL: 12,
    },
  },
  {
    id: "69b9184807dee5c7ea02ce0b",
    slug: "maroon-handcrafted-shirt",
    name: "Maroon Handcrafted Shirt",
    description:
      "Regular fit shirt made from a cotton and linen blend fabric. Featuring a hand embroidered motif at the above side of your beautiful heart. Patterns include shirt collar and long sleeves with buttoned cuffs",
    price: 1399,
    mrp: 1599,
    discount: 13,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/04",
    color: "MAROON",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_main.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_1.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_2.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_3.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_4.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_5.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_6.jpg",
      "/assets/products/MAROON_HANDCRAFTED_SHIRT/MAROON_HANDCRAFTED_SHIRT_view_7.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.4,
    reviews: 167,
    badge: "Bestseller",
    stock: {
      XS: 13,
      S: 12,
      M: 12,
      L: 12,
      XL: 13,
      XXL: 2,
      XXXL: 3,
    },
  },
  {
    id: "69b916a807dee5c7ea02cddb",
    slug: "coffee-brown-floral-shirt",
    name: " Coffee Brown Floral Shirt",
    description:
      "The cuban collar relaxed fit shirt with loose fit short sleeves for more moments to enjoy your casual moments at work or at the vacation. Spotted beautiful and elegant contrast  hand embroidered floral vel pattern motif. ",
    price: 1299,
    mrp: 1599,
    discount: 19,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/06",
    color: "COFFEE BROWN",
    sizes: ["S", "M", "L", "XXL", "XL"],
    images: [
      "/assets/products/COFFEE_BROWN_FLORAL_SHIRT/COFFEE_BROWN_FLORAL_SHIRT_main.jpg",
      "/assets/products/COFFEE_BROWN_FLORAL_SHIRT/COFFEE_BROWN_FLORAL_SHIRT_view_1.jpg",
      "/assets/products/COFFEE_BROWN_FLORAL_SHIRT/COFFEE_BROWN_FLORAL_SHIRT_view_2.jpg",
      "/assets/products/COFFEE_BROWN_FLORAL_SHIRT/COFFEE_BROWN_FLORAL_SHIRT_view_3.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.5,
    reviews: 184,
    badge: "Limited",
    stock: {
      XS: 4,
      S: 3,
      M: 3,
      L: 3,
      XL: 4,
      XXL: 5,
      XXXL: 6,
    },
  },
  {
    id: "69b914be07dee5c7ea02cd8d",
    slug: "floral-embroidered-sketch-shirt",
    name: " Floral Embroidered Sketch Shirt",
    description:
      " Peach pink handcrafted mens shirt featuring sketch inspired intricate hand embroidered detailing, loose fit pattern to allow fluid movement and a subtle visual flow. Natural cotton fabric is durable and breathable, amplified with  A structured, relaxed fit and easily stiffed  for ample room for statement view.",
    price: 1899,
    mrp: 1999,
    discount: 5,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/02",
    color: "PEACH PINK",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_main.jpg",
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_view_1.jpg",
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_view_2.jpg",
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_view_3.jpg",
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_view_4.jpg",
      "/assets/products/FLORAL_EMBROIDERED_SKETCH_SHIRT/FLORAL_EMBROIDERED_SKETCH_SHIRT_view_5.jpg",
    ],
    fabric: "Premium cotton-linen blend",
    occasion: "Elevated everyday wear",
    rating: 4.6,
    reviews: 201,
    badge: "New",
    stock: {
      XS: 7,
      S: 6,
      M: 6,
      L: 6,
      XL: 7,
      XXL: 8,
      XXXL: 9,
    },
  },
  {
    id: "69b9118607dee5c7ea02cd18",
    slug: "hand-embroidered-floral-shirt",
    name: "Hand Embroidered Floral Shirt",
    description:
      "Cuban collar relax fit half sleeve shirt made from a linen and cotton blend fabric. Featuring a front side symmetrical dedicated handworked floral motif inspired from the Indian historical arts.",
    price: 2799,
    mrp: 2999,
    discount: 7,
    category: "Floral",
    sku: "M26/SS/FLORAL/CS/01",
    color: "Off White",
    sizes: ["S", "M", "L", "XL", "XXL"],
    images: [
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_main.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_1.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_2.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_3.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_4.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_5.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_6.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_7.jpg",
      "/assets/products/HAND_EMBROIDERED_FLORAL_SHIRT/HAND_EMBROIDERED_FLORAL_SHIRT_view_8.jpg",
    ],
    fabric: "Cotton 80% and Linen 20%, 100% Natural fabric",
    occasion: "Elevated everyday wear",
    rating: 4.7,
    reviews: 38,
    badge: "Bestseller",
    stock: {
      XS: 10,
      S: 9,
      M: 9,
      L: 9,
      XL: 10,
      XXL: 11,
      XXXL: 12,
    },
  },
]
